#!/bin/sh

TARGET_DIR=/home/alex/tmp
LIBNAME=DeSiGNAR
VERSION=0.5.1a

if [ -d $TARGET_DIR/$LIBNAME ]; then
  rm -r $TARGET_DIR/$LIBNAME
fi

mkdir $TARGET_DIR/$LIBNAME
mkdir $TARGET_DIR/$LIBNAME/bin
mkdir $TARGET_DIR/$LIBNAME/include
mkdir $TARGET_DIR/$LIBNAME/lib
mkdir $TARGET_DIR/$LIBNAME/obj
mkdir $TARGET_DIR/$LIBNAME/samples
mkdir $TARGET_DIR/$LIBNAME/src

cp LICENSE Makefile $TARGET_DIR/$LIBNAME
cp include/*.H $TARGET_DIR/$LIBNAME/include
cp samples/*.C $TARGET_DIR/$LIBNAME/samples
cp src/*.C $TARGET_DIR/$LIBNAME/src

cd $TARGET_DIR
tar -cjvf $LIBNAME-$VERSION.tbz $LIBNAME
rm -r $LIBNAME
cd -
